"""Downloadable invoice documents: a PDF per invoice, a ZIP of a batch's PDFs, and a CSV of an invoice list.

Documents are rendered from the stored invoice and its lines only. Nothing is recalculated here: the totals on
the PDF are the totals recorded when the invoice was issued (and reconciled), so a download can never disagree
with the ledger.
"""
import csv
import io
import zipfile
from datetime import timedelta

from sqlalchemy import select

from ..models import Invoice, InvoiceBatch, Client, Agent, Contract, Setting
from .export import escape_cell as safe
from .audit import log

SELF_BILLING_VAT_WORDING = "The VAT shown is your output tax due to HMRC"
_LATIN1_FIX = str.maketrans({"–": "-", "—": "-", "’": "'", "‘": "'", "“": '"', "”": '"', "…": "...", "·": "-", "→": "->",
                             "×": "x", " ": " "})


def _t(v) -> str:
    """Core PDF fonts are Latin-1: map common punctuation, replace anything else rather than fail."""
    return str(v if v is not None else "").translate(_LATIN1_FIX).encode("latin-1", "replace").decode("latin-1")


def _money(v) -> str:
    return f"£{v:,.2f}"


def _company(db) -> dict:
    st = db.get(Setting, "company")
    c = st.value if st else {}
    return {"name": c.get("name") or "Company name not set", "address": c.get("address") or "",
            "vat_number": c.get("vat_number") or ""}


def document_kind(inv: Invoice) -> str:
    if inv.kind == "CLIENT":
        return "INVOICE"
    return "SELF-BILLING INVOICE" if inv.self_billed else "PURCHASE RECORD"


def render_pdf(db, inv: Invoice) -> bytes:
    from fpdf import FPDF

    company = _company(db)
    batch = db.get(InvoiceBatch, inv.batch_id)
    if inv.kind == "CLIENT":
        party = db.get(Client, inv.client_id)
        con = db.scalar(select(Contract).where(Contract.client_id == party.id, Contract.status == "ACTIVE"))
        terms = (con.terms or {}) if con else {}
        seller = (company["name"], company["address"], f"VAT {company['vat_number']}" if company["vat_number"] else "")
        buyer = (party.name, terms.get("billing_address", ""), "")
        days = terms.get("payment_days")
        due = f"{inv.issue_date + timedelta(days=int(days)):%d/%m/%Y} ({days} days)" if days else ""
    else:
        party = db.get(Agent, inv.agent_id)
        seller = (party.name, party.region or "", f"VAT {party.vat_number}" if party.vat_number and inv.vat else
                  ("Not VAT registered" if not inv.vat else ""))
        buyer = (company["name"], company["address"], f"VAT {company['vat_number']}" if company["vat_number"] else "")
        due = ""

    pdf = FPDF(format="A4", unit="mm")
    pdf.set_margins(15, 12, 15)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_title(_t(f"{document_kind(inv).title()} {inv.number}"))
    pdf.set_author(_t(company["name"]))
    pdf.alias_nb_pages()

    def footer():
        pdf.set_y(-12)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(120, 128, 140)
        pdf.cell(0, 5, _t(f"{inv.number} - page {pdf.page_no()}/{{nb}} - generated by FlowGuard from the issued record"),
                 align="C")
        pdf.set_text_color(0, 0, 0)
    pdf.footer = footer
    pdf.add_page()

    navy = (11, 31, 58)
    pdf.set_fill_color(*navy)
    pdf.rect(0, 0, 210, 6, "F")
    pdf.set_xy(15, 14)
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*navy)
    pdf.cell(110, 9, _t(document_kind(inv)))
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(0, 0, 0)
    meta = [("Number", inv.number), ("Date", f"{inv.issue_date:%d/%m/%Y}")]
    if due:
        meta.append(("Payment due", due))
    if inv.self_billing_ref:
        meta.append(("Self-billing agreement", inv.self_billing_ref))
    if inv.po_refs:
        meta.append(("PO", ", ".join(inv.po_refs)[:60]))
    meta.append(("Batch", batch.reference if batch else ""))
    y = 14
    for k, v in meta:
        pdf.set_xy(120, y)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(90, 99, 115)
        pdf.cell(32, 5, _t(k))
        pdf.set_font("Helvetica", "B" if k == "Number" else "", 9)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(43, 5, _t(v), align="R")
        y += 5

    def block(x, title, lines):
        pdf.set_xy(x, max(y, 32) + 4)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(90, 99, 115)
        pdf.cell(85, 5, _t(title), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        for i, ln in enumerate(l for l in lines if l):
            pdf.set_x(x)
            pdf.set_font("Helvetica", "B" if i == 0 else "", 10 if i == 0 else 9)
            pdf.multi_cell(85, 5, _t(ln), new_x="LMARGIN", new_y="NEXT")
        return pdf.get_y()

    if inv.kind == "CLIENT":
        y1 = block(15, "From", seller)
        y2 = block(110, "Bill to", buyer)
    elif inv.self_billed:
        y1 = block(15, "Supplier (invoice raised by the customer under a self-billing agreement)", seller)
        y2 = block(110, "Customer", buyer)
    else:
        y1 = block(15, "Supplier", seller)
        y2 = block(110, "Customer", buyer)
    pdf.set_y(max(y1, y2) + 4)

    if inv.self_billed and inv.vat:
        pdf.set_fill_color(233, 238, 246)
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.multi_cell(0, 6, _t(f"SELF-BILLING. {SELF_BILLING_VAT_WORDING}."), fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
    elif inv.self_billed:
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _t("SELF-BILLING. Supplier not VAT registered: no VAT is charged."), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
    elif inv.kind == "AGENT":
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _t("The supplier sends its own invoice to us. This record is the amount we expect to pay, "
                                "for checking against that invoice."), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # line items
    widths = (22, 128, 30)
    pdf.set_fill_color(*navy)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8.5)

    def header_row():
        pdf.set_fill_color(*navy)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8.5)
        for w, h, a in zip(widths, ("Job", "Description", "Net"), ("L", "L", "R")):
            pdf.cell(w, 7, h, fill=True, align=a)
        pdf.ln()
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 8.5)

    header_row()
    for i, ln in enumerate(inv.lines):
        if pdf.get_y() > 270:
            pdf.add_page()
            header_row()
        if i % 2:
            pdf.set_fill_color(248, 250, 253)
        desc = ln.description + (f" (PO {ln.po_number})" if ln.po_number else "")
        pdf.cell(widths[0], 6, _t(f"FG-{ln.job_id:05d}"), fill=bool(i % 2))
        pdf.cell(widths[1], 6, _t(desc[:95]), fill=bool(i % 2))
        pdf.cell(widths[2], 6, _t(_money(ln.net)), fill=bool(i % 2), align="R")
        pdf.ln()

    # totals
    if pdf.get_y() > 250:
        pdf.add_page()
    pdf.ln(3)
    rate = float(inv.vat_rate) * 100
    for label, val, bold in (("Net", inv.net, False), (f"VAT {rate:.0f}%" if rate == int(rate) else f"VAT {rate}%", inv.vat, False),
                             ("Total", inv.gross, True)):
        pdf.set_x(120)
        pdf.set_font("Helvetica", "B" if bold else "", 10 if bold else 9)
        pdf.cell(45, 6, _t(label))
        pdf.cell(30, 6, _t(_money(val)), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(90, 99, 115)
    pdf.multi_cell(0, 4.5, _t(f"VAT treatment: {inv.vat_treatment}. VAT calculated once on the invoice net. "
                              f"{len(inv.lines)} line(s)."), new_x="LMARGIN", new_y="NEXT")
    return bytes(pdf.output())


def filename(inv: Invoice) -> str:
    return f"{inv.number}.pdf"


def invoice_pdf(db, actor: str, role: str, inv: Invoice) -> bytes:
    data = render_pdf(db, inv)
    log(db, actor, "INVOICE_DOWNLOADED", "invoice", inv.number, new="PDF", role=role)
    db.commit()
    return data


def batch_zip(db, actor: str, role: str, batch: InvoiceBatch) -> bytes:
    invs = list(db.scalars(select(Invoice).where(Invoice.batch_id == batch.id).order_by(Invoice.number)))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for inv in invs:
            z.writestr(filename(inv), render_pdf(db, inv))
    log(db, actor, "INVOICE_BATCH_DOWNLOADED", "invoice_batch", batch.reference, new=f"{len(invs)} PDFs", role=role)
    db.commit()
    return buf.getvalue()


def list_csv(rows: list[dict]) -> str:
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["Invoice", "Side", "Party", "Party code", "Issued", "Lines", "Net", "VAT", "Gross", "VAT rate", "Status",
                "Exported"])
    for r in rows:
        side = "Client sales" if r["kind"] == "CLIENT" else ("Agent self-billed" if r["self_billed"] else "Agent purchase")
        w.writerow([safe(r["number"]), side, safe(r["party"] or ""), safe(r["party_code"] or ""), r["issue_date"], r["lines"],
                    r["net"], r["vat"], r["gross"], r["vat_rate"], r["status"], "Yes" if r["exported"] else "No"])
    return out.getvalue()
